name: Continuous Deployment to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH and Pull Code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Starting the automated deployment process..."
            cd ~/somethinc_pipeline
            git reset --hard HEAD
            git pull origin main
            echo "Deployment completed"